---
apiVersion: v1
kind: Namespace
metadata:
  name: law-service

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: law-service-travis
  namespace: k8s-cluster-config
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: law-service-travis
  namespace: law-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: law-service-travis
    namespace: law-service
